# Generated by Django 5.1.4 on 2025-09-29 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villager_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('road', 'Road Issue'), ('water', 'Water Supply'), ('electricity', 'Electricity'), ('sanitation', 'Sanitation'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='complaint_photos/')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='complaint_voice/')),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('feedback', models.CharField(blank=True, choices=[('happy', '🙂 Happy'), ('neutral', '😐 Neutral'), ('angry', '😡 Angry')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
