# Generated by Django 5.1.4 on 2025-09-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='complaint_voice/%Y/%m/%d/'),
        ),
    ]
