# Generated by Django 5.1.4 on 2025-09-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('photo', models.ImageField(upload_to='complaint_photos/')),
                ('qr_code', models.ImageField(upload_to='complaint_qrcodes/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
