# Generated by Django 5.1.4 on 2025-10-04 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='issue',
            field=models.TextField(verbose_name='समस्या का विवरण'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=100, verbose_name='स्थान'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(max_length=100, verbose_name='शिकायतकर्ता का नाम'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(upload_to='complaints/photos/', verbose_name='फोटो'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/qrcodes/', verbose_name='QR कोड'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='दर्ज करने का समय'),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=100, verbose_name='गाँव का नाम')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
