# Generated by Django 5.1.4 on 2025-10-09 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_issue_alter_complaint_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'प्रशासन प्रोफाइल', 'verbose_name_plural': 'प्रशासन प्रोफाइल'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'शिकायत', 'verbose_name_plural': 'शिकायतें'},
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='बनाने की तारीख'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='सक्रिय है'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='फोन नंबर'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_staff',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='निर्धारित स्टाफ'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='शिकायत आईडी'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='बनाने की तारीख'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, verbose_name='विवरण'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalated_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='एस्केलेट किया गया'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='feedback',
            field=models.CharField(blank=True, choices=[('happy', '🙂'), ('neutral', '😐'), ('angry', '😡')], max_length=10, null=True, verbose_name='फीडबैक'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='हल होने की तारीख'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_breached',
            field=models.BooleanField(default=False, verbose_name='SLA उल्लंघन'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('submitted', 'रिपोर्ट दर्ज हुई'), ('verified', 'सत्यापित'), ('resolved', 'हल हुई'), ('feedback', 'फीडबैक'), ('performance', 'प्रदर्शन'), ('escalation', 'एस्केलेशन'), ('dashboard', 'डैशबोर्ड')], default='submitted', max_length=20, verbose_name='स्थिति'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='trust_badge',
            field=models.BooleanField(default=False, verbose_name='ट्रस्ट बैज'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='सत्यापित की तारीख'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='complaints/voice_notes/', verbose_name='वॉइस नोट'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='उपयोगकर्ता'),
        ),
        migrations.CreateModel(
            name='ComplaintTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'रिपोर्ट दर्ज हुई'), ('verified', 'सत्यापित'), ('resolved', 'हल हुई'), ('feedback', 'फीडबैक'), ('performance', 'प्रदर्शन'), ('escalation', 'एस्केलेशन'), ('dashboard', 'डैशबोर्ड')], max_length=20, verbose_name='स्थिति')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='नोट्स')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='अपडेट की तारीख')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='complaints.complaint', verbose_name='शिकायत')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='अपडेट किया गया')),
            ],
            options={
                'verbose_name': 'शिकायत ट्रैकिंग',
                'verbose_name_plural': 'शिकायत ट्रैकिंग',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, verbose_name='पदनाम')),
                ('phone_number', models.CharField(max_length=15, verbose_name='फोन नंबर')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय है')),
                ('admin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='complaints.adminprofile', verbose_name='प्रशासन प्रोफाइल')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='उपयोगकर्ता')),
            ],
            options={
                'verbose_name': 'स्टाफ सदस्य',
                'verbose_name_plural': 'स्टाफ सदस्य',
            },
        ),
    ]
